const LOGIN_MODAL_OPEN = "LOGIN_MODAL_OPEN";
const LOGIN_MODAL_CLOSE = "LOGIN_MODAL_CLOSE";

const MENU_MODAL_OPEN = "MENU_MODAL_OPEN";
const MENU_MODAL_CLOSE = "MENU_MODAL_CLOSE";

const USER_LOGIN = "USER_LOGIN";

const GAME_LEADERBOARD_RECEIVE = "GAME_LEADERBOARD_RECEIVE";

const GAME_FIELD_OPEN = "GAME_FIELD_OPEN";
const GAME_FIELD_CLOSE = "GAME_FIELD_CLOSE";

export {LOGIN_MODAL_OPEN, LOGIN_MODAL_CLOSE, USER_LOGIN, MENU_MODAL_CLOSE, MENU_MODAL_OPEN, GAME_LEADERBOARD_RECEIVE, GAME_FIELD_OPEN, GAME_FIELD_CLOSE};