const LOGIN_MODAL_OPEN = "LOGIN_MODAL_OPEN";
const LOGIN_MODAL_CLOSE = "LOGIN_MODAL_CLOSE";

const MENU_MODAL_OPEN = "MENU_MODAL_OPEN";
const MENU_MODAL_CLOSE = "MENU_MODAL_CLOSE";

const GAME_FIELD_OPEN = "GAME_FIELD_OPEN";
const GAME_FIELD_CLOSE = "GAME_FIELD_CLOSE";

const PLAYER_LOGIN = "PLAYER_LOGIN";

const GAME_LEADERBOARD_RECEIVE = "GAME_LEADERBOARD_RECEIVE";

const SET_PLAYER_LOCATION = "SET_PLAYER_LOCATION";
const MODIFY_PLAYER_LOCATION_X = "MODIFY_PLAYER_LOCATION_X";
const MODIFY_PLAYER_LOCATION_Y = "MODIFY_PLAYER_LOCATION_Y";

const SET_PLAYER_VECTOR = "SET_PLAYER_VECTOR";

export {LOGIN_MODAL_OPEN, LOGIN_MODAL_CLOSE, PLAYER_LOGIN, MENU_MODAL_CLOSE, MENU_MODAL_OPEN, GAME_LEADERBOARD_RECEIVE,
    GAME_FIELD_OPEN, GAME_FIELD_CLOSE, SET_PLAYER_LOCATION, MODIFY_PLAYER_LOCATION_X, MODIFY_PLAYER_LOCATION_Y};