const LOGIN_MODAL_OPEN = "LOGIN_MODAL_OPEN";
const LOGIN_MODAL_CLOSE = "LOGIN_MODAL_CLOSE";

const MENU_MODAL_OPEN = "MENU_MODAL_OPEN";
const MENU_MODAL_CLOSE = "MENU_MODAL_CLOSE";

const GAME_FIELD_OPEN = "GAME_FIELD_OPEN";
const GAME_FIELD_CLOSE = "GAME_FIELD_CLOSE";

const PLAYER_LOGIN = "PLAYER_LOGIN";

const SET_MOUSE_POSITION = "SET_MOUSE_POSITION";

const SET_GAME_RESULT = "SET_GAME_RESULT";

export {LOGIN_MODAL_OPEN, LOGIN_MODAL_CLOSE, PLAYER_LOGIN, MENU_MODAL_CLOSE, MENU_MODAL_OPEN, GAME_FIELD_OPEN, GAME_FIELD_CLOSE, SET_MOUSE_POSITION, SET_GAME_RESULT};